### ISSUE TITLE
crash using tree-sitter-policyspace [missing file]

### ISSUE THREAD

**Issue by wolf-jonathan** [wolfj123/vscode-tree-sitter-policymodels#1]
**crash error:**

Activating tree-sitter...
extension.js:90
RuntimeError: abort(Error: ENOENT: no such file or directory, open '..\..\Code-Projects\vscode-tree-sitter\parsers\tree-sitter-policyspace.wasm'). Build with -s ASSERTIONS=1 for more info.
	at process.de (e:\Code-Projects\vscode-tree-sitter\node_modules\web-tree-sitter\tree-sitter.js:1:10170)
	at process.emit (events.js:208:15)
	at processPromiseRejections (internal/process/promises.js:201:33)
	at processTicksAndRejections (internal/process/task_queues.js:86:32)

**Comment by wolf-jonathan** [comment]
this extension requires the parser to be packaged WebAssembly. unfortunately the packaging scripts only work in linux
